#!/bin/sh
if ! [ -x /var/lib/jenkins/workspace/TestAfterArtifactoryUpdate/chromium.chromedriver ]; then
    echo "" >&2
    echo "Command '$0' requires the chromium snap to be installed." >&2
    echo "Please install it with:" >&2
    echo "" >&2
    echo "snap install chromium" >&2
    echo "" >&2
    exit 1
fi
exec /var/lib/jenkins/workspace/TestAfterArtifactoryUpdate/chromium.chromedriver "$@"
